### ISSUE TITLE
Can't see orchestra pod while deploying OpenUnison

### ISSUE THREAD

**Issue by kushan22** [PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide#12]
Hello Team,

I am trying to follow chapter 7's openunison's deployment. I was able to deploy the operator using helm and then I also created an account on Tremolo Security portal where I got Idp metadata url. 
Now when I try to deploy orchestra using values.yaml it says it has been deployed but I don't see the pod in my cluster. 

I get this when I install it:
![image](https://user-images.githubusercontent.com/14822234/119209889-ef5dc180-ba6e-11eb-99ea-4d1125923b72.png)

but I don't see the pod:
![image](https://user-images.githubusercontent.com/14822234/119209903-01d7fb00-ba6f-11eb-8f66-1fc308f06f6c.png)

I am using Windows WSL2 with Ubuntu 20.04.02 and my docker is running on my wsl Ubuntu connected via Windows. I have a kind cluster already deployed with Control plane and worker node running. 

Please help I am trying to get ahead in the book and I am enjoying reading it but this has really made me scratch my head.

**Comment by kushan22** [comment]
This is openunison operator logs:
![image](https://user-images.githubusercontent.com/14822234/119210437-b410c200-ba71-11eb-9b63-410c0bec64ac.png)

It says unable to resolve tremolo security portal.

**Comment by kushan22** [comment]
Anyone please ?

**Comment by mlbiam** [comment]
Sorry for the delay.  Yes, looks like you have a DNS issue in your cluster.  curling works:

```
curl -v https://portal.apps.tremolo.io/idp-test/metadata/7e6cc1fb-51de-4d3a-96fa-0325b57a1929
*   Trying 35.175.93.158:443...
* Connected to portal.apps.tremolo.io (35.175.93.158) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.apps.tremolo.io
*  start date: Feb 15 00:00:00 2021 GMT
*  expire date: Mar 16 23:59:59 2022 GMT
*  subjectAltName: host "portal.apps.tremolo.io" matched cert's "*.apps.tremolo.io"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x11db950)
> GET /idp-test/metadata/7e6cc1fb-51de-4d3a-96fa-0325b57a1929 HTTP/2
> Host: portal.apps.tremolo.io
> user-agent: curl/7.75.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< date: Fri, 28 May 2021 09:23:15 GMT
< content-length: 2073
< server: nginx/1.17.7
< set-cookie: openunison-orchestra=1622193796.379.114.430292; Path=/; Secure; HttpOnly
< set-cookie: tremolosession=eyJpdiI6IkdiMExtTG5Ca3pHdmNVZ2lXRWlDRXdcdTAwM2RcdTAwM2QiLCJlbmNyeXB0ZWRSZXF1ZXN0IjoiK2hKMVVWY3FkQ2VoZG5VczdhYldpdU1yTksxVUdiREMrYkFkc25IQUZIVHJuTGlISEx5OTJrRVVjbmJOSVV0TCJ9; Domain=portal.apps.tremolo.io; Secure; HttpOnly; Path=/;
< set-cookie: openSession=f71ad4eaad6c6510eaef7ff9f581f8c3a7836e3ee; path=/; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:00 GMT
< strict-transport-security: max-age=15724800; includeSubDomains
< 
<?xml version="1.0" encoding="UTF-8"?><EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" ID="fc9cdc28b706b57eee19eb0664103bb14661899c0" entityID="https://portal.apps.tremolo.io/idp-test"><IDPSSODescriptor WantAuthnRequestsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><KeyDescriptor use="signing"><KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#"><X509Data><X509Certificate>MIIDtjCCAp6gAwIBAgIGAXmRhiDFMA0GCSqGSIb3DQEBCwUAMHwxFDASBgNVBAMMC2lkcC1zaWduaW5nMQwwCgYDVQQLDANkZXYxHzAdBgNVBAoMFlRyZW1vbG8gU2VjdXJpdHksIEluYy4xEjAQBgNVBAcMCVRoZSBDbG91ZDERMA8GA1UECAwIT2YgQmVpbmcxDjAMBgNVBAYTBUVhcnRoMB4XDTIxMDUyMTAwNDIzN1oXDTMxMDUyMDAwNDIzN1owfDEUMBIGA1UEAwwLaWRwLXNpZ25pbmcxDDAKBgNVBAsMA2RldjEfMB0GA1UECgwWVHJlbW9sbyBTZWN1cml0eSwgSW5jLjESMBAGA1UEBwwJVGhlIENsb3VkMREwDwYDVQQIDAhPZiBCZWluZzEOMAwGA1UEBhMFRWFydGgwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAjzDY/MDlsFOQtlQh5MQP21+DUAtHbevsjJiPq5esIfT8eeOo7YuPkitd9jO1uZxpyNMCElr5x1SaK+MgoIYHDaT1vT1IcWLBIYQgL8E0hCYmIEfba2z9N5MPX33mjK83uzGXevtQdlSIy2deokW8UOsjzIQxh61bnbIHF92lpOilmvgWh2udz0TSZx1NhVTNVziH06uWPdIReSW/vA4TAHjlc+Vv5/F+MoDwzf0jcsJELZs7fVACyaPTiH/DE890dktjq+VfYUVYJByIZmRrUKlWW8Ih60bt6rdOHg9vSPK4NAFoBTcS/ycvD9a1pP6Ai/2WvShtW1/8IbLNkEBBAgMBAAGjPjA8MA4GA1UdDwEB/wQEAwICBDASBgNVHSUBAf8ECDAGBgRVHSUAMBYGA1UdEQQPMA2CC2lkcC1zaWduaW5nMA0GCSqGSIb3DQEBCwUAA4IBAQBTcPc0TGq9rqs17mr90gN50C09qrcs4j4H9Pjy9Lrc+9UOLgkYLd55EYIVc0UrsT7VeHH2LEpUsqxz/hlL/UXH4ko+js6v8P39FEe8OGosANpQgAD5OWVEdnZdsCmAQP0GwjQJRVMbsOFcpuDxOyAvN5mIMNNB3BdR+T3GpVvVWa0JbPVhhOgbqB5lzUl0Q1RFdB3bZ0RNohLQA4yIXKsCuIB5Szxk4rkVWQARLcUgGuvnKZl8O/tqC+0CB1JswU0hY+kyEwPvGlVWPoS9G6r+gqvUvQUBntTowjI93WI00S4B6Kd/tvlTd1QNErORLK9NYDzyF7ja3z+BLYf1ZArh</X509Certificate></X509Data></KeyInfo></KeyDescriptor><SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://portal.apps.tremolo.io/idp-test/index.jsp"/><SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://portal.apps.tremolo.io/idp-test/index.jsp"/></IDPSSODescriptor></EntityDescriptor>
* Connection #0 to host portal.apps.tremolo.io left intact
```

if you exec into the operator, can you use curl to hit portal.apps.tremolo.io?

**Comment by kushan22** [comment]
@mlbiam Hi Sorry I was out of town for memorial day weekend.
I tried exec into the operator and using curl. Its not working. Same error could not resolve host.
![image](https://user-images.githubusercontent.com/14822234/120220451-58c59900-c202-11eb-8d0d-b0fa8dcecd75.png)


Should I add it to host file of my container ?

**Comment by kushan22** [comment]
I can hit portal.apps.tremolo.io from my docker host but from inside the container or my cluster I am not able to hit it

**Comment by kushan22** [comment]
Is there anything I can do to resolve this ? I have been trying a lot but I can't get it to work
Please help ?

**Comment by ssurovich** [comment]
Hi Kushan - 

When you mention that "I am using Windows WSL2 with Ubuntu 20.04.02 and my docker is running on my wsl Ubuntu connected via Windows." - Are you using Docker for Desktop with WSL2 support, or did you try to install Genie to add systemd to a pure Ubuntu 20 running Docker in WSL2?

It looks like you aren't resolving internet address, or missing internet connectivity in general from a Container.   Knowing the answer to the above will help me look at it.

As one side test - can you run curl 172.217.12.142   from a container?   It should come back with a Google reference, just a quick test.

**Comment by kushan22** [comment]
Yes its docker desktop on windows with WSL support. I can't curl anything from within the openunison container

**Comment by ssurovich** [comment]
Thanks for the confirmation - Im going to reproduce the environment on my laptop - I have an idea of what the issue may be.  It may be later tonight since I need to deploy Docker on Windows - I do most of my testing on a straight Ubuntu / RHEL Virtual Machine(s).

**Comment by kushan22** [comment]
Okay thankyou :)

**Comment by ssurovich** [comment]
Hi Kushan - 

Apologies on the questions - I think youre running a routing issue and running Docker on WSL2 and KinD gets into a nesting game - So, Im curious about any IP ranges that may be overlapping.  

I just tried it on my laptop and my containers can connect to the internet - but my home network setup is likely different from yours.

Can you verify - Are the IP ranges for each of the following on different subnets:

1.  Windows Host  (Typical ipconfig to get the address)
2.  WSL2 VM (Run ip addr in a WSL Ubuntu session for the address)
3.  Your Docker Network IP range for the kind network   (You could just exec into one of the running containers in Docker, the Control plane or worker node and use ip addr)
4.  Finally - In the OpenUnison pod, get the pod address

Also, how did you install KinD - Did you attempt to use our script, or did you use the example from the KinD documentation?

There are multiple articles in other repos / websites where people have issues with WSL2 and Internet access, with different resolutions ranging from a temp folder that was compressed, to scrips to stop and delete files.  The issue you are having is related to running under WSL2, we just need to figure out what is breaking in the communication path.

I dont think this will buy us much - but if you deploy a quick nginx container (kubectl run nginx --image=nginx)  - Then exec into it and curl 1.1.1.1 (Cloudflare DNS).  Im assuming it will fail - but this will verify that the issue is in the network flow.

**Comment by kushan22** [comment]
This is my windows host config:
![image](https://user-images.githubusercontent.com/14822234/121762681-274fa600-cafd-11eb-8533-e4d6a1f63739.png)

This is ubuntu WSL2 ifconfig results:
![image](https://user-images.githubusercontent.com/14822234/121762691-3fbfc080-cafd-11eb-9280-2834103a454d.png)

This is my container ip addr config:
![image](https://user-images.githubusercontent.com/14822234/121762750-844b5c00-cafd-11eb-9b03-43b2a3de8c8b.png)


I installed Kind using the scripts provided in the book.

This is what I am getting from nginx container:

![image](https://user-images.githubusercontent.com/14822234/121762817-e60bc600-cafd-11eb-859d-b2cb47138e34.png)

**Comment by ssurovich** [comment]
Thanks for the details (Great details BTW for troubleshooting).

The config looks good I dont see any ranges that would overlap, which is something I have seen in the past - so thats great to rule out.

The last screen is important, that shows that the NGINX container can access the internet, at lest by IP address. So one more (again, apologies for asking you to do a lot of extra tasks) - lets use netshoot so we have access to more tools for any troubleshooting.

kubectl run tmp-shell --rm -i --tty --image nicolaka/netshoot -- /bin/bash

This will take about a minute before you get a bash prompt - once you have a prompt, can you curl to 1.1.1.1 again?  I assume this will work without any issues.  Next, do an nsloookup on www.google.com - netshoot includes nslookup.

If the curl to 1.1.1.1 works but the curl to www.google.com fails, we need to check name resolution.  If the www.google.com fails, can you paste the contents of /etc/resolv.conf from the netshoot container.

One last nslookup test - can you nslookup kube-dns.kube-system.svc in the netshoot container.

Im guessing the answer is no to this, but did you create any network policies in K8s that would limit egress traffic?

Thanks - These steps will help to figure out if its name resolution issue. 

We'll get there :)

**Comment by kushan22** [comment]
So, the curl to 1.1.1.1 works but nslookup fails from netshoot container. The contents of resolv.conf are also shown in image below.
![image](https://user-images.githubusercontent.com/14822234/121817759-e4024e00-cc48-11eb-9cca-7e7e84d75712.png)

nslookup of kube dns is shown below:
![image](https://user-images.githubusercontent.com/14822234/121817797-1f048180-cc49-11eb-987f-c85b8080552e.png)

I did create any network policy. 


This is my cluster config:
![image](https://user-images.githubusercontent.com/14822234/121817831-5c690f00-cc49-11eb-9b09-f2e183ea1d89.png)

**Comment by ssurovich** [comment]
Thanks again for the information.

So it does look like a name resolution issue - CoreDNS can resolve K8s cluster entries, but it's not forwarding to resolve names outside of the cluster.   On my WSL2, running Docker Desktop w/ WSL2 integration, is not having the issue - I can resolve names outside of the cluster (Which makes troubleshooting this difficult).

Im assuming you didnt edit the coredns configmap?     I hate to keep asking you to post things, but the issue is bugging me :)

Could you post you coredns configmap?  (kubectl get cm  coredns -n kube-system  -o yaml)

Anything in the CoreDNS logs that may help??  (kubectl logs -n kube-system -l k8s-app=kube-dns)

One thing you could try, but you shouldnt need to by default (But there are a few ?? in this that are tough to troubleshoot without access to a system :)  )   -  We could edit the CoreDNS configmap to forward directly to either your router's IP or an external DNS server like 1.1.1.1 (or Googles) - If you wanted to try this:

1.  Edit the coredns ConfigMap (kubectl edit cm coredns -n kube-system )
2. Look for the forward line and replace the /etc/resolv.conf portion of the line with 1.1.1.1  (Example below)
                 
        forward . 1.1.1.1

3. Save and exit
4. Restart the CoreDNS pods (kubectl delete pods -n kube-system -l k8s-app=kube-dns)

Once the new CoreDNS pods are up and running, try the nslookup for www.google.com in the netshoot container.

**Comment by kushan22** [comment]
This is my core dns config map:
![image](https://user-images.githubusercontent.com/14822234/121987458-20739e00-cd5e-11eb-9cd5-0d2f85591d7b.png)

This is core dns logs:
![image](https://user-images.githubusercontent.com/14822234/121987527-426d2080-cd5e-11eb-87bd-307e67661759.png)

Yup after editing the config map to forward to 1.1.1.1 I am able to nslookup from within the container:
![image](https://user-images.githubusercontent.com/14822234/121987873-f40c5180-cd5e-11eb-9947-83270b536acb.png)

**Comment by ssurovich** [comment]
@kushan22  - Excellent, (sort of) - It shouldnt need that, but its a fix to get you moving along in the book now.   You should be able to keep that fix implemented and try the OpenUnison deployment again.  

Just in case you havent played with the coredns config before - the default forward line tells coredns to forward a request using the hosts /etc/resolv.conf configuration.  It looks like thats the main issue, and in a pure Linux system we could look at that easily - but on WSL2, Im not sure how to check that since the VM doesnt have an interactive console (last time I checked).   The CoreDNS page has a good read on the forward option: https://coredns.io/plugins/forward/

Let me know if the OU failure that you previously had is resolved, once you try.

**Comment by kushan22** [comment]
Hi @ssurovich 
Yes, this solves the problem but I would still like to get to the core of the problem and get a good fix for that. I am gonna do a readup on that. 
Thankyou so much for your help :)

**Comment by kushan22** [comment]
I am getting this error while trying to hit openunison dashboard. Do you know what could be the issue ?
![image](https://user-images.githubusercontent.com/14822234/122300859-86c70080-cec5-11eb-87d7-e23376d14d19.png)

**Comment by ssurovich** [comment]
Glad to help - Im with you, Im still curious what the fix is, potentially, the WSL GIT Issues might be able to offer some feedback?  Im still going to look at it as I get time, but since mine works on WSL2, its a tough one to look at from my side.   (I really hoped mine would have failed so I could look into it).

On the OU Dash, Ill see if Marc can offer any suggestions - But the first thing to check is the Ingress rule, and of course - I need to ask - Does Ingress work for any other workloads?

@mlbiam - Adding you as well since we are past the original DNS issues.

**Comment by kushan22** [comment]
Nevermind I got it worked. Thankyou so much. Closing this issue for now

**Comment by ssurovich** [comment]
Excellent!  Thanks for the update - and glad you got it working.   Pesky problem with the DNS, but its a good learning experience.  I am a firm believer that when things break, or may not go as expected, you learn a lot :)  (although its frustrating, no doubt)
