### ISSUE TITLE
there is no chapter5

### ISSUE THREAD

**Issue by derklauer** [PacktPublishing/Kubernetes-and-Docker-The-Complete-Guide#9]

**Comment by ssurovich** [comment]
Hi @derklauer -

I'm not sure what your issue is referring to, there is no information, just the title "there is no chapter5"?    I am assuming that you might be looking for a directory in the repo for Chapter 5 exercises?   If this is correct, there are no exercises for Chapter 5 that required any code in the repo - Chapter 5 is a Bootcamp for Kubernetes objects and was designed as a refresher for anyone that may have been away from K8s for awhile, or a crash course for newer readers to become familiar with most of the base Kubernetes objects.  

While we do have some example commands and code in the book, they aren't required for the other chapters and most are very short and can be typed manually.

Is there something in particular you were looking for?
